# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbs_2 <- function(R, F, Z, X, risk, r_f, nsamps) {
    .Call(`_BayesPortfolio_gibbs_2`, R, F, Z, X, risk, r_f, nsamps)
}

gibbs_fast_2 <- function(R, F, Z, X, risk, r_f, nsamps) {
    .Call(`_BayesPortfolio_gibbs_fast_2`, R, F, Z, X, risk, r_f, nsamps)
}

gibbs_fast_hedge <- function(R, F, Z, X, risk, r_f, nsamps, A_r_prior_mean, A_r_prior_precision, A_f_prior_mean, A_f_prior_precision, A_z_prior_mean, A_z_prior_precision, nu, V_F, V_Z, n_hedge = 1L) {
    .Call(`_BayesPortfolio_gibbs_fast_hedge`, R, F, Z, X, risk, r_f, nsamps, A_r_prior_mean, A_r_prior_precision, A_f_prior_mean, A_f_prior_precision, A_z_prior_mean, A_z_prior_precision, nu, V_F, V_Z, n_hedge)
}

gibbs_fast <- function(R, F, Z, X, risk, r_f, nsamps) {
    .Call(`_BayesPortfolio_gibbs_fast`, R, F, Z, X, risk, r_f, nsamps)
}

gibbs_slow_hedge <- function(R, F, Z, X, risk, r_f, nsamps, A_r_prior_mean, A_r_prior_precision, A_f_prior_mean, A_f_prior_precision, A_z_prior_mean, A_z_prior_precision, nu, V_F, V_Z) {
    .Call(`_BayesPortfolio_gibbs_slow_hedge`, R, F, Z, X, risk, r_f, nsamps, A_r_prior_mean, A_r_prior_precision, A_f_prior_mean, A_f_prior_precision, A_z_prior_mean, A_z_prior_precision, nu, V_F, V_Z)
}

gibbs <- function(R, F, X, Xi, Z, T, N, K, M, nsamp, burnin, tau) {
    .Call(`_BayesPortfolio_gibbs`, R, F, X, Xi, Z, T, N, K, M, nsamp, burnin, tau)
}

log_posterior <- function(R, F, Z, X) {
    .Call(`_BayesPortfolio_log_posterior`, R, F, Z, X)
}

rmultireg_IG_multirun <- function(Y, X, betabar_all, A, nu, B_output, Sigma_output, nsamps) {
    invisible(.Call(`_BayesPortfolio_rmultireg_IG_multirun`, Y, X, betabar_all, A, nu, B_output, Sigma_output, nsamps))
}

rmultireg_IG_singlerun_alone <- function(Y, X, betabar_all, A, nu) {
    .Call(`_BayesPortfolio_rmultireg_IG_singlerun_alone`, Y, X, betabar_all, A, nu)
}

rmultireg_IG_singlerun_fast <- function(Y, X, betabar_all, A, nu, beta_mat, sigmasq_vec) {
    invisible(.Call(`_BayesPortfolio_rmultireg_IG_singlerun_fast`, Y, X, betabar_all, A, nu, beta_mat, sigmasq_vec))
}

rmultireg_IG_singlerun <- function(Y, X, betabar_all, A, nu, beta_mat, sigmasq_vec) {
    invisible(.Call(`_BayesPortfolio_rmultireg_IG_singlerun`, Y, X, betabar_all, A, nu, beta_mat, sigmasq_vec))
}

rmultireg_IG <- function(Y, X, betabar_all, A, nu, R, keep) {
    .Call(`_BayesPortfolio_rmultireg_IG`, Y, X, betabar_all, A, nu, R, keep)
}

rmultireg_IW_multirun <- function(Y, X, Bbar, A, nu, V, B_output, Sigma_output, nsamps) {
    invisible(.Call(`_BayesPortfolio_rmultireg_IW_multirun`, Y, X, Bbar, A, nu, V, B_output, Sigma_output, nsamps))
}

rmultireg_IW_singlerun_fast <- function(Y, X, Bbar, A, nu, V, B, Sigma) {
    invisible(.Call(`_BayesPortfolio_rmultireg_IW_singlerun_fast`, Y, X, Bbar, A, nu, V, B, Sigma))
}

rmultireg_IW_singlerun <- function(Y, X, Bbar, A, nu, V, B, Sigma) {
    invisible(.Call(`_BayesPortfolio_rmultireg_IW_singlerun`, Y, X, Bbar, A, nu, V, B, Sigma))
}

runireg_BP <- function(y, X, betabar, A, nu, ssq, R, keep, nprint) {
    .Call(`_BayesPortfolio_runireg_BP`, y, X, betabar, A, nu, ssq, R, keep, nprint)
}

runireg_singlerun <- function(y, X, betabar, A, nu, ssq, beta, sigmasq) {
    invisible(.Call(`_BayesPortfolio_runireg_singlerun`, y, X, betabar, A, nu, ssq, beta, sigmasq))
}

runiregGibbs <- function(y, X, betabar, A, nu, ssq, sigmasq, R, keep, nprint) {
    .Call(`_BayesPortfolio_runiregGibbs`, y, X, betabar, A, nu, ssq, sigmasq, R, keep, nprint)
}

sampler1 <- function(R, F, nsamps, burnin) {
    .Call(`_BayesPortfolio_sampler1`, R, F, nsamps, burnin)
}

sampler2 <- function(R, F, Z, nsamps, burnin, gamma, r_f, icept_z_only = TRUE) {
    .Call(`_BayesPortfolio_sampler2`, R, F, Z, nsamps, burnin, gamma, r_f, icept_z_only)
}

rmatNorm <- function(M, U, V) {
    .Call(`_BayesPortfolio_rmatNorm`, M, U, V)
}

Mahalanobis <- function(x, center, cov) {
    .Call(`_BayesPortfolio_Mahalanobis`, x, center, cov)
}

dmvnorm_arma <- function(x, mean, sigma, log = FALSE) {
    .Call(`_BayesPortfolio_dmvnorm_arma`, x, mean, sigma, log)
}

