# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbs_2 <- function(R, F, X, Xi, Z, T, N, K, M, nsamp, burnin, tau) {
    .Call(`_BayesPortfolio_gibbs_2`, R, F, X, Xi, Z, T, N, K, M, nsamp, burnin, tau)
}

gibbs <- function(R, F, X, Xi, Z, T, N, K, M, nsamp, burnin, tau) {
    .Call(`_BayesPortfolio_gibbs`, R, F, X, Xi, Z, T, N, K, M, nsamp, burnin, tau)
}

rmultireg_IG_singlerun <- function(Y, X, betabar_all, A, nu, beta_mat, sigmasq_vec) {
    .Call(`_BayesPortfolio_rmultireg_IG_singlerun`, Y, X, betabar_all, A, nu, beta_mat, sigmasq_vec)
}

rmultireg_IG <- function(Y, X, betabar_all, A, nu, R, keep) {
    .Call(`_BayesPortfolio_rmultireg_IG`, Y, X, betabar_all, A, nu, R, keep)
}

rmultireg_singlerun <- function(Y, X, Bbar, A, nu, V) {
    .Call(`_BayesPortfolio_rmultireg_singlerun`, Y, X, Bbar, A, nu, V)
}

runiregGibbs_rcpp_loop <- function(y, X, betabar, A, nu, ssq, sigmasq, R, keep, nprint) {
    .Call(`_BayesPortfolio_runiregGibbs_rcpp_loop`, y, X, betabar, A, nu, ssq, sigmasq, R, keep, nprint)
}

rmatNorm <- function(M, U, V) {
    .Call(`_BayesPortfolio_rmatNorm`, M, U, V)
}

rwishart_bayesm <- function(nu, V) {
    .Call(`_BayesPortfolio_rwishart_bayesm`, nu, V)
}

